# Generated by Django 2.2.1 on 2019-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='amount',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
