# Generated by Django 2.2.1 on 2019-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190511_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
