# Generated by Django 2.2.1 on 2019-05-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190511_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='categories',
            new_name='category',
        ),
    ]
