# Generated by Django 2.2.1 on 2019-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190511_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
