# Generated by Django 2.2.1 on 2019-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
