# Generated by Django 2.1.7 on 2019-05-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_catname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='catname',
        ),
    ]
